name: furchild_snowflake
version: 1.0.0
config-version: 2

profile: default
model-paths: ["models"]

flags:
  warn_error: false 

models:
  furchild_snowflake:
    staging:
      +schema: SILVER
      +materialized: table
    marts:
      +materialized: table
      +schema: GOLD

      commerce:
        +tags: ['mart', 'commerce']
        dims:
          +materialized: table     
        facts:
          +materialized: incremental
          +on_schema_change: append_new_columns
          +persist_docs:
            relation: true
            columns: true
        aggregates:
          +materialized: table

